[package]
name = "simphoto"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.6.1", features = ["derive"] }
image = { version = "0.23", default-features = false, features = ["jpeg", "png", "gif", "bmp", "webp", "pnm", "tiff"] }
img_hash = "3.2.0"
kamadak-exif = "0.6.1"
rayon = "1.12.0"
walkdir = "2.5.0"

[target."cfg(not(windows))".dependencies]
libheif-rs = { version = "2.7.0", default-features = false, features = ["v1_17"] }
